### ISSUE TITLE
Inconsistency in data property naming

### ISSUE THREAD

**Issue by lostpebble** [near/near-lake-framework-js#13]
Hi,

I actually wanted to put this in a discussion but I see you don't have it available.

I'm just curious why the data structures have been created differently between the more "native" types, which we have seen before with the Near Public Indexer and the Rust implementations, and those of the TypeScript implementation.

For example, a transaction data structure in TypeScript:

```ts
export type Transaction = {
  signerId: string;
  publicKey: string;
  nonce: number;
  receiverId: string;
  actions: Action[];
  signature: string;
  hash: string;
};
```

And the same data in Rust (which also matches the indexer's db and our historical Near structures):

```rust
pub struct SignedTransactionView {
    pub signer_id: AccountId,
    pub public_key: PublicKey,
    pub nonce: Nonce,
    pub receiver_id: AccountId,
    pub actions: Vec<ActionView>,
    pub signature: Signature,
    pub hash: CryptoHash,
}
```

Its not so great to have such different property naming schemes for the same structures across the ecosystem- because it means each system would need to transform the data to whichever way they've built their utilities to accept it.

Understandably, the first one is because of Rust's naming guidelines- I think this was the original format ? The same naming format is perfectly acceptable with TypeScript as well, so I'm curious why it wasn't just kept the same for consistency.

---

This actually makes me wonder what the raw files look like on S3. I haven't had a chance to take a look yet (not sure its possible), I've only interacted with them through the framework so far.

**Comment by frol** [comment]
camelCase is the most common code style for JS/TS, so instead of leading people into mixing cases in their code base, we expose the interfaces in the code style that is the norm for the target language. We don't expect people to write their indexers in a mix of languages, so the problem of alignment between Rust and JS code styles seems irrelevant to me. We used to use snake_case in NEAR Explorer whenever we receive data from RPC and DB, and it was quite an ugly mix, especially when it comes to deeply nested structures that you don't want to manually re-map on the Explorer side and near-api-js did not do this mapping.

> This actually makes me wonder what the raw files look like on S3.

They are JSON files with snake_case formatting.

**Comment by lostpebble** [comment]
>We don't expect people to write their indexers in a mix of languages, so the problem of alignment between Rust and JS code styles seems irrelevant to me

Unfortunately real-world usage in this case differs, especially for consumers of Near blockchain data. Many people have interacted with the Public Indexer or use other services which expose the blockchain and the data structures returned are using the standard snake_case formatting. I'm not sure that "common code style for a language" or "it looks ugly" is a good enough reason to completely change property naming- as this could cause all kinds of issues down the line, such as if people index this data "as is" in some database and only later realize down the line that this data now doesn't align with what is standard for the Near ecosystem.

Especially for people consuming data from Near Lake- the purpose is probably to store it in some DB down the line and query on it. If they now use the Rust implementation for whatever reason, the data structures are different. This could be surprising. I would have just indexed things directly had I not picked up that the data structures look different to what we had previously interacted with.

Its not a huge deal- but yea, it does mean for all our frontend utilities which interacted with this data, we now will need to transform the data. Which means the data has been transformed twice now, since it used to actually be snake_case when it was a file. Seems wasteful.

Could there maybe be a way for us to request the data with this library without transformation of property naming? Perhaps an option:

```ts
const lakeConfig: types.LakeConfig = {
  s3BucketName: "near-lake-data-mainnet",
  s3RegionName: "eu-central-1",
  // ...
  propertyNamingFormat: "native"
};
```

**Comment by frol** [comment]
> if people index this data "as is" in some database and only later realize down the line that this data now doesn't align with what is standard for the Near ecosystem.

I personally don't see that as a risk as internal usage could be anything (and for JS folks camelCase is the preferred naming convention) while public API should be designed separately and should not be blindly passed down the line.

> Especially for people consuming data from Near Lake- the purpose is probably to store it in some DB down the line and query on it.

I would encourage them to consider defining the API structure for the database on their own to avoid such problems in the first place. It is always a risk if a low-level interface affects the high-level one.

> Could there maybe be a way for us to request the data with this library without transformation of property naming?

That could be an option, but there will be a need to design how to deal with the TypeScript types as they currently use camelCase: https://github.com/near/near-lake-framework-js/blob/main/src/types.ts

Feel free to propose a PR. Alternatively, you may fork this repo and remove the naming conversion and drop the types, and run with the fork.

**Comment by lostpebble** [comment]
Thanks for the responses. I'll take a look at the code base and consider creating a PR that keeps the snake_case naming conventions, while maintaining correct TypeScript typing.
