### ISSUE TITLE
Release latest changes on NPM

### ISSUE THREAD

**Issue by sarin-dotin** [near/near-lake-framework-js#15]
The last 2 commits didn't publish to NPM. It would be nice if we could have the latest changes in NPM

**Comment by sarin-dotin** [comment]
@frol @khorolets

**Comment by frol** [comment]
@sarin-dotin I am not the maintainer of NEAR Lake anymore. I passed my ownership to @pkudinov

**Comment by khorolets** [comment]
1.0.5 is published https://www.npmjs.com/package/near-lake-framework?activeTab=versions
