### ISSUE TITLE
block.events does not process logs properly

### ISSUE THREAD

**Issue by bucanero** [near/near-lake-framework-js#38]
I’m building a simple indexer, and I’m getting a weird behavior when using `block.events()`.
Context:
Near Block `#61321189`  has an executed receipt `AVeR4o6MWKYMhjJV8x6ZNk9U9kQYm1qbiN8bBaQQ4rWG` from `paras.near` , and it has an EVENT_JSON following the nep171 standard.

Yet, if I run my simple indexer using QueryAPI with debug mode, I add block 61321189 to debug and run my code, calling `block.events()` shows that Events are not parsed correctly.

I expected that `standard/version/event/data` would be parsed and populated from the log.

**Comment by morgsmccauley** [comment]
@bucanero `block.events` is a function, and therefore must be called as `block.events()`.

Testing this locally did highlight an issue with the function though - the events were not being parsed correctly. I've raised a PR to fix it.
