### ISSUE TITLE
Shard info is missing

### ISSUE THREAD

**Issue by danielwpz** [near/near-lake-framework-js#46]
Hey I frequently get errors like: `Failed to fetch 106732712/shard_3.json. Retrying in 200ms NoSuchKey: The specified key does not exist.`

What could be the reason for it? is there any data lost?

**Comment by morgsmccauley** [comment]
Block and shard data are written to different files and therefore become available at different times. Your indexer most likely pulled the block while the shards were being uploaded, causing the error you see. As the error states, it will retry automatically and is therefore not a problem.
