### ISSUE TITLE
Can't catch Amazon S3 exception

### ISSUE THREAD

**Issue by liketurbo** [near/near-lake-framework-js#9]
After launching code from the example, from time to time you'll receive an error saying "The specified key does not exist", which goes straight to stdout and you can't handle it with `try...catch` or `Promise.prototype.catch()`

```typescript
import { startStream, types } from "near-lake-framework";

const lakeConfig: types.LakeConfig = {
  s3BucketName: "near-lake-data-mainnet",
  s3RegionName: "eu-central-1",
  startBlockHeight: 63804051,
};

async function handleStreamerMessage(
  streamerMessage: types.StreamerMessage
): Promise<void> {
  console.log(
    `Block #${streamerMessage.block.header.height} Shards: ${streamerMessage.shards.length}`
  );
}

(async () => {
  await startStream(lakeConfig, handleStreamerMessage);
})();
```

**Comment by frol** [comment]
It is semi-related to #2, and specifically to potential redesign of the stream handling. However, I wonder how would you like to handle missing access key? I basically see two options:

1. Inform (currently it just points to stdout)
2. Exit (let supervisor/monitoring tools to surface the issue to the system operator)

**Comment by liketurbo** [comment]
> It is semi-related to #2, and specifically to potential redesign of the stream handling. However, I wonder how would you like to handle missing access key? I basically see two options:
> 
>     1. Inform (currently it just points to stdout)
> 
>     2. Exit (let supervisor/monitoring tools to surface the issue to the system operator)

@frol I don't. I just wanna stop it from littering my logs by catching and not handling the error

**Comment by frol** [comment]
We can probably make a config option to control how to handle the missing access key (keep retrying or exit). @liketurbo Would you be interested to work on it and submit a PR?

**Comment by liketurbo** [comment]
@frol For now, I just ignore errors with the code "NoSuchKey", as It's unclear how an end user can properly handle this, nor that he can handle this, but just writing error to `stderr` does nothing (if don't count littering logs 😊).

**Comment by liketurbo** [comment]
Also we can change `startStream` callback to more traditional one, which is with an error parameter - `(error, data) => void`

**Comment by liketurbo** [comment]
> Also we can change `startStream` callback to more traditional one, which is with an error parameter - `(error, data) => void`

But this will change API 🤔

**Comment by frol** [comment]
Let’s not change the APIs. We may consider adding a third parameter (optional) to startStream to expect an error callback

**Comment by liketurbo** [comment]
@frol But what you thinking about just to silence the error?

**Comment by frol** [comment]
@liketurbo that would not be helpful to users who forgot to provide the key or revoked the key. This will be worse than spamming with the error to the output since this error is not recoverable

**Comment by liketurbo** [comment]
> @liketurbo that would not be helpful to users who forgot to provide the key or revoked the key. This will be worse than spamming with the error to the output since this error is not recoverable

But wait, I thought that the cause of the error was that we're trying to get a file which doesn't exist.
```javascript
    const data = await client.send(
      new GetObjectCommand({
        Bucket: bucketName,
        Key: `${normalizeBlockHeight(blockHeight)}/shard_${shardId}.json`, // <-- Probably, this file doesn't exist [yet]
        RequestPayer: "requester",
      })
    );
```
So users have no input on that 🤔

**Comment by liketurbo** [comment]
> @liketurbo that would not be helpful to users who forgot to provide the key or revoked the key. This will be worse than spamming with the error to the output since this error is not recoverable

And I don't think that it's "not recoverable", cause it calls itself recursively
```javascript
  // ...
  } catch (err) {
    console.error(
      `Failed to fetch ${blockHeight}/shard_${shardId}.json. Retrying immediately`,
      err
    );
    return await fetchSingleShard(client, bucketName, blockHeight, shardId); // <-- Calling itself again 
  }
```
